=== yoshaul/javaders/src/main/resources/config/levels.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!--
          ~ This file is part of Javaders.
          ~ Copyright (c) Yossi Shaul
          ~
          ~ Javaders is free software: you can redistribute it and/or modify
          ~ it under the terms of the GNU General Public License as published by
          ~ the Free Software Foundation, either version 3 of the License, or
          ~ (at your option) any later version.
          ~
          ~ Javaders is distributed in the hope that it will be useful,
          ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
          ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
          ~ GNU General Public License for more details.
          ~
          ~ You should have received a copy of the GNU General Public License
          ~ along with Javaders.  If not, see <http://www.gnu.org/licenses/>.
          -->

<!ELEMENT gameLevels (lastLevel, level+)>
<!ELEMENT lastLevel EMPTY>
<!ATTLIST lastLevel levelNum CDATA #REQUIRED>
<!ELEMENT level (backgroundImage?, enemyShips+)>
<!ATTLIST level levelNum CDATA #REQUIRED>
<!ELEMENT backgroundImage (#PCDATA)>
<!ELEMENT enemyShips (shipType, numberOfShips)>
<!ELEMENT shipType (#PCDATA)>
<!ELEMENT numberOfShips (#PCDATA)>

=== yoshaul/javaders/src/main/resources/config/levels.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
  ~ This file is part of Javaders.
  ~ Copyright (c) Yossi Shaul
  ~
  ~ Javaders is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ Javaders is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with Javaders.  If not, see <http://www.gnu.org/licenses/>.
  -->

<!DOCTYPE gameLevels SYSTEM "levels.dtd">

<gameLevels>

	<lastLevel levelNum="50"/>

	<level levelNum = "1">
		<backgroundImage>bg2_1024.jpg</backgroundImage>
		<enemyShips>
			<shipType>1</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>
	</level>

	<level levelNum = "2">
		<enemyShips>
			<shipType>1</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "3">
		<enemyShips>
			<shipType>1</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>2</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "4">
		<enemyShips>
			<shipType>1</shipType>
			<numberOfShips>4</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>2</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "5">
		<enemyShips>
			<shipType>1</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>2</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>3</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "6">
		<enemyShips>
			<shipType>2</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>3</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "7">
		<enemyShips>
			<shipType>1</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>2</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>3</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>4</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>		
	</level>	

	<level levelNum = "8">
		<enemyShips>
			<shipType>1</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>3</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>4</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "9">
		<enemyShips>
			<shipType>1</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>2</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>3</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>4</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
	</level>
	
	<level levelNum = "10">
		<enemyShips>
			<shipType>201</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "11">
		<backgroundImage>bg3_1024.jpg</backgroundImage>
		<enemyShips>
			<shipType>21</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "12">
		<enemyShips>
			<shipType>21</shipType>
			<numberOfShips>4</numberOfShips>
		</enemyShips>		
	</level>
	
	<level levelNum = "13">
		<enemyShips>
			<shipType>21</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>22</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "14">
		<enemyShips>
			<shipType>23</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
	</level>
	
	<level levelNum = "15">
		<enemyShips>
			<shipType>23</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>26</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "16">
		<enemyShips>
			<shipType>21</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>23</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>24</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>25</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>		
	</level>
	
	<level levelNum = "17">
		<enemyShips>
			<shipType>26</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
	</level>
	
	<level levelNum = "18">
		<enemyShips>
			<shipType>21</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>22</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>23</shipType>
			<numberOfShips>4</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>24</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "19">
		<enemyShips>
			<shipType>27</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "20">
		<enemyShips>
			<shipType>202</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>		
	</level>
	
	<level levelNum = "21">
		<backgroundImage>bg1_1024.jpg</backgroundImage>
		<enemyShips>
			<shipType>21</shipType>
			<numberOfShips>7</numberOfShips>
		</enemyShips>		
	</level>
	
	<level levelNum = "22">
		<enemyShips>
			<shipType>22</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>23</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>26</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "23">
		<enemyShips>
			<shipType>23</shipType>
			<numberOfShips>4</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>24</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>25</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>26</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "24">
		<enemyShips>
			<shipType>23</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>25</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>26</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "25">
		<enemyShips>
			<shipType>24</shipType>
			<numberOfShips>4</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>27</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "26">
		<enemyShips>
			<shipType>24</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>25</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>27</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "27">
		<enemyShips>
			<shipType>21</shipType>
			<numberOfShips>6</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>23</shipType>
			<numberOfShips>6</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>26</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>		
	</level>
	
	<level levelNum = "28">
		<enemyShips>
			<shipType>22</shipType>
			<numberOfShips>7</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>23</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>25</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>26</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>		
	</level>
	
	<level levelNum = "29">
		<enemyShips>
			<shipType>21</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>22</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>23</shipType>
			<numberOfShips>4</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>24</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>25</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>26</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>
		<enemyShips>
			<shipType>27</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>						
	</level>
	
	<level levelNum = "30">
		<enemyShips>
			<shipType>203</shipType>
			<numberOfShips>1</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "31">
		<backgroundImage>bg4.jpg</backgroundImage>
		<enemyShips>
			<shipType>41</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>		
	</level>

	<level levelNum = "32">
		<enemyShips>
			<shipType>41</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>43</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>
	
	<level levelNum = "33">
		<enemyShips>
			<shipType>42</shipType>
			<numberOfShips>3</numberOfShips>
		</enemyShips>		
		<enemyShips>
			<shipType>43</shipType>
			<numberOfShips>2</numberOfShips>
		</enemyShips>
	</level>

	<level levelNum = "34">
